import subprocess
import shutil
from pathlib import Path
import pandas as pd
import numpy as np

GPSBABEL_BIN = Path(__file__).resolve().parent / "bin" / "GPSBabel" / "gpsbabel.exe"


def convert_nmea(input_file, output_file, output_format, input_format="nmea", extra_args=None):
    """
    Convert an NMEA GPS file to any format supported by gpsbabel.
    """
    # ==========================================
    # WBS 1.1.1 & 1.1.2: Directory Layout & GPSBabel Binary Setup
    # ==========================================
    
    # 1.1.2 (a): Check if the bundled binary exists in the project layout
    if GPSBABEL_BIN.exists():
        gpsbabel_cmd = str(GPSBABEL_BIN)
    else:
        # 1.1.2 (b): Fallback to checking the system PATH
        gpsbabel_cmd = shutil.which("gpsbabel")

    if gpsbabel_cmd is None:
        raise FileNotFoundError(
            f"gpsbabel not found. Expected bundled binary at {GPSBABEL_BIN} or a PATH install."
        )

    # ==========================================
    # WBS 1.1.3: GPSBabel Python Wrapper & Exporter
    # ==========================================
    
    # 1.1.3 (a): Validate and resolve input/output file paths
    input_path = Path(input_file)
    if not input_path.exists():
        raise FileNotFoundError(f"Input file not found: {input_file}")

    output_path = Path(output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # 1.1.3 (b): Construct the base CLI command array
    cmd = [gpsbabel_cmd, "-i", input_format, "-f", str(input_path.absolute())]

    if extra_args:
        cmd.extend(extra_args)

    dummy_bin = None
    
    # 1.1.3 (c): Smart handling for proprietary mtk-bin CSV exports
    # Some GPS loggers require a dummy file flag to export CSV properly
    if output_format.lower() == "mtk-bin" and output_path.suffix.lower() == ".csv":
        actual_format = f"mtk-bin,csv={str(output_path.absolute())}"
        dummy_bin = output_path.parent / "dummy.bin"
        cmd.extend(["-o", actual_format, "-F", str(dummy_bin.absolute())])
    else:
        # Standard export mapping
        cmd.extend(["-o", output_format, "-F", str(output_path.absolute())])

    # 1.1.3 (d): Execute the subprocess
    result = subprocess.run(cmd, capture_output=True, text=True)

    # 1.1.3 (e): Clean up temporary junk files generated by the CLI
    if dummy_bin and dummy_bin.exists():
        dummy_bin.unlink()

    # 1.1.3 (f): Error handling and logging
    if result.returncode != 0:
        raise RuntimeError(
            f"gpsbabel failed (exit {result.returncode}):\n{result.stderr.strip()}"
        )

    return str(output_path)

def clean_gps_data(csv_path: str) -> dict:
    """
    Reads a GPSBabel-generated CSV, cleans the data, and separates 
    track points from waypoints.
    """
    # ==========================================
    # WBS 1.1.4: Pandas data cleaning + waypoint extraction
    # ==========================================
    
    # 1.1.4 (a): Load the raw CSV
    df = pd.read_csv(csv_path)

    # 1.1.4 (b): Standardize column names (lowercase and strip spaces)
    df.columns = [col.strip().lower() for col in df.columns]

    # 1.1.4 (c): Drop critical NaNs (Must have lat/lon)
    df = df.dropna(subset=['latitude', 'longitude'])

    # 1.1.4 (d): Combine and parse datetime
    if 'date' in df.columns and 'time' in df.columns:
        df['timestamp'] = pd.to_datetime(df['date'] + ' ' + df['time'], errors='coerce')
    
    # 1.1.4 (e): Extract Waypoints vs. Track Points based on 'name'
    if 'name' in df.columns:
        waypoints_df = df[df['name'].notna() & (df['name'] != '')].copy()
        route_df = df[df['name'].isna() | (df['name'] == '')].copy()
    else:
        waypoints_df = pd.DataFrame() 
        route_df = df.copy()

    # 1.1.4 (f): Sort chronologically
    if 'timestamp' in route_df.columns:
        route_df = route_df.sort_values(by='timestamp').reset_index(drop=True)

    # ==========================================
    # WBS 1.1.5: Stationary point removal & filtering
    # ==========================================
    
    # Drop rows where the person hasn't moved from the exact same Lat/Lon.
    if 'latitude' in route_df.columns and 'longitude' in route_df.columns:
        # Round to 5 decimal places (~1.1 meters precision) to account for GPS jitter
        route_df['lat_round'] = route_df['latitude'].round(5)
        route_df['lon_round'] = route_df['longitude'].round(5)
        
        # NEW ADDITION: Count how many times this exact coordinate appears.
        # Since it's ~1 record per second, this equals the seconds spent at this location.
        route_df['duplicate_count'] = route_df.groupby(['lat_round', 'lon_round'])['lat_round'].transform('size')
        
        # Keep rows only if they differ from the previous row (dropping the consecutive duplicates)
        # But because we added the count above, the row we KEEP will now store 
        # the total number of seconds the person stood there!
        route_df = route_df.loc[(route_df['lat_round'] != route_df['lat_round'].shift()) | 
                                (route_df['lon_round'] != route_df['lon_round'].shift())]
        
        # Clean up temp rounding columns, but KEEP our new 'duplicate_count' column
        route_df = route_df.drop(columns=['lat_round', 'lon_round'])

    # ==========================================
    # WBS 1.1.6: Fallback parser for timestampless files
    # ==========================================
    
    # Check if 'timestamp' column is missing or entirely empty (NaT)
    if 'timestamp' not in route_df.columns or route_df['timestamp'].isnull().all():
        print("⚠️ Warning: No timestamps found in raw data! Generating artificial 1-second timeline...")
        
        start_time = pd.Timestamp.now()
        route_df['timestamp'] = pd.date_range(start=start_time, periods=len(route_df), freq='1S')
        
    else:
        # Fill any randomly missing gaps in an otherwise valid timeline
        route_df['timestamp'] = route_df['timestamp'].ffill()

    print(f"Data cleaned! Found {len(route_df)} route points and {len(waypoints_df)} waypoints.")

    return {
        "route": route_df,
        "waypoints": waypoints_df
    }